### ISSUE TITLE
Debería haber un requirements.txt

### ISSUE THREAD

**Issue by cgosorio** [AdrianArnaiz/TFG-Neurodegenerative-Disease-Detection#43]
Me he dado cuenta al intentar ejecutar la demo en un nuevo entorno virtual python. Me faltaban los módulos `ttkthemes`, `mutagen` `resampy`, `soundfile`, `tensorflow`, `pygame`, `keras` y `matplotlib`. Pero puede haber otras dependencias en tu proyecto. Todas ellas deberían estar en un archivo requirements.txt. Desde el entorno virtual de python donde estés haciendo el desarrollo ejecuta:
```
pip freeze > requirements.txt
```
Aún instalando las dependencias, no he sido capaz de ejecutar la demo. Me da el error:
```
ImportError: cannot import name 'NavigationToolbar2TkAgg'
```

**Comment by cgosorio** [comment]
Acabo de hacer la prueba en una máquina Linux y tras instalar las dependencias, me da el mismo error.

**Comment by cgosorio** [comment]
He conseguido superar algunos de los errores siguiendo las instrucciones dadas en https://github.com/jni/skan/issues/66. Básicamente, se trata de cambiar `NavigationToolbar2TkAgg`por `NavigationToolbar2Tk`.

Aún así da otro error:
```
_tkinter.TclError: bad argument "zoomed": must be normal, iconic, or withdrawn
```
que he solucionado cambiando `self.root.state('zoomed')`  a `self.root.state('normal')`, el problema está en que en Linux no se soporta ese estado.

A pesar de todo esto, sigue habiendo un error:
```
OSError: Unable to open file (unable to open file: name = 'prediccion/vggish_weights.ckpt', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```
para el que he creado una nueva issue.

**Comment by AdrianArnaiz** [comment]
**Al principio del desarrollo NO creee un entorno virtual.**
Por ello, ahora debo crearlo, activarlo e ir instalando todas las dependencias necesarias para poder generar el requirements.txt y facilitar que alguien que quiera probar el código pueda instalar las dependencias en un sólo paso.
* [ ] Crear entorno virtual
* [ ] Instalar dependenciar
* [ ] Generar requirements.txt
