### ISSUE TITLE
Falta el archivo src/demo/prediccion/vggish_weights.ckpt

### ISSUE THREAD

**Issue by cgosorio** [AdrianArnaiz/TFG-Neurodegenerative-Disease-Detection#44]
Me temo que ese archivo no está incluida en el repositorio de GitHub, con lo que la demo falla eventualmente al intentar cargarlo.

**Comment by AdrianArnaiz** [comment]
Así es. Ese y otro archivo son demasiado grandes para subirles. ¿Añado un link dentro del readme del directorio demo?

**Comment by AdrianArnaiz** [comment]
Se subió el link al archivo equivocado.

**Comment by AdrianArnaiz** [comment]
Se arregló y se dio instrucciones de la instalación.
