### ISSUE TITLE
Añadir URLs a noticias y web sobre el proyecto

### ISSUE THREAD

**Issue by cgosorio** [AdrianArnaiz/TFG-Neurodegenerative-Disease-Detection#50]
Estaría bien añadir en el README.md un listado de enlaces a las web y notas de prensa que mencionan el proyecto. José me acaba de pasar las siguientes como respuesta a una consulta que le he hecho, pero sería mejor tenerlas aquí todas centralizadas.

> [18:28, 31/5/2020] Jose Francisco Diez Pastor: Nota de prensa ubu https://www.ubu.es/noticias/dos-prototipos-de-la-ubu-utilizan-la-inteligencia-artificial-para-detectar-y-tratar-enfermedades
> [18:30, 31/5/2020] Jose Francisco Diez Pastor: Los premios https://www.ubu.es/agenda/entrega-de-premios-y-lanzamiento-de-nuevas-convocatorias-curso-2019-2020-prototipos-orientados-al-mercado-vii-convocatoria-prueba-concepto
> [18:30, 31/5/2020] Jose Francisco Diez Pastor: luego de terceros hay más notas de prensa
> [18:31, 31/5/2020] Jose Francisco Diez Pastor: https://diariodevalladolid.elmundo.es/articulo/innovadores/voces-anticipan-temblores/20191217130131365000.html

**Comment by AdrianArnaiz** [comment]
Añadidas al Readme la compilación de noticias encontradas en los diferentes medios.
